#!/bin/sh

case $# in
  0 )
    dscreen toggle
    exit 0;;

  1 )
    case $1 in
      left )
        xrandr --output eDP1 --auto
        xrandr --output HDMI1 --auto
        xrandr --output HDMI1 --right-of eDP1
        xrandr --output HDMI1 --primary
        ponymix -d alsa_output.pci-0000_00_03.0.hdmi-stereo-extra1 set-default
        exit 0;;

      right )
        xrandr --output eDP1 --auto
        xrandr --output HDMI1 --auto
        xrandr --output HDMI1 --left-of eDP1
        xrandr --output HDMI1 --primary
        ponymix -d alsa_output.pci-0000_00_03.0.hdmi-stereo-extra1 set-default
        exit 0;;

      off )
        xrandr --output eDP1 --auto
        xrandr --output HDMI1 --off
        ponymix -d alsa_output.pci-0000_00_1b.0.analog-stereo set-default
        exit 0;;

      toggle )
        case `xrandr -q | grep -c "*"` in
          1 )
            dscreen on;;
          2 )
            dscreen off;;
        esac;;
    esac;;
esac

echo "invalid arguments"
exit 1
